### PR TITLE
Use shared_ptr to protect members which are passed to capture list of lambda function.

### LINKED ISSUE #2079: SIGSEGV with gcr.io/istio-release/proxyv2:release-1.1-20181222-09-15
```
2019-01-12T01:31:06.256829Z	info	Reconciling retry (budget 3)
2019-01-12T01:31:06.256962Z	info	Epoch 0 starting
2019-01-12T01:31:06.258207Z	info	Envoy command: [-c /etc/istio/proxy/envoy-rev0.json --restart-epoch 0 --drain-time-s 45 --parent-shutdown-time-s 60 --service-cluster istio-ingressgateway --service-node router~10.44.3.12~istio-ingressgateway-b77977775-h56ft.istio-system~istio-system.svc.cluster.local --max-obj-name-len 189 --allow-unknown-fields -l warning --v2-config-only]
[2019-01-12 01:31:06.291][000262][warning][upstream] [external/envoy/source/common/config/grpc_mux_impl.cc:268] gRPC config stream closed: 14, no healthy upstream
[2019-01-12 01:31:06.291][000262][warning][upstream] [external/envoy/source/common/config/grpc_mux_impl.cc:51] Unable to establish new stream
[2019-01-12 01:31:06.761][000262][warning][config] [src/envoy/utils/mixer_control.cc:171] ExtractInfo  metadata missing:
[2019-01-12 01:31:06.762][000262][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_mux_subscription_lib/common/config/grpc_mux_subscription_impl.h:70] gRPC config for type.googleapis.com/envoy.api.v2.Listener rejected: Error adding/updating listener 0.0.0.0_443: error adding listener '0.0.0.0:443': multiple filter chains with the same matching rules are defined
[2019-01-12 01:31:06.770][000268][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:125] Caught Segmentation fault, suspect faulting address 0x80
2019-01-12T01:31:06.851486Z	warn	Epoch 0 terminated with an error: signal: segmentation fault (core dumped)
2019-01-12T01:31:06.851575Z	warn	Aborted all epochs
```

debug backtrace
```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/local/bin/envoy -c /etc/istio/proxy/envoy-rev0.json --restart-epoch 0 --dr'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  istio::mixer::v1::config::client::HttpClientConfig::transport (this=0x0) at bazel-out/k8-dbg/genfiles/external/mixerapi_git/mixer/v1/config/client/client_config.pb.h:1533
1533	bazel-out/k8-dbg/genfiles/external/mixerapi_git/mixer/v1/config/client/client_config.pb.h: No such file or directory.
[Current thread is 1 (Thread 0x7f8450c0f700 (LWP 520))]
(gdb) bt
#0  istio::mixer::v1::config::client::HttpClientConfig::transport (this=0x0) at bazel-out/k8-dbg/genfiles/external/mixerapi_git/mixer/v1/config/client/client_config.pb.h:1533
#1  0x00000000004d4ca5 in Envoy::Http::Mixer::Config::check_cluster[abi:cxx11]() const (this=0x0) at ./src/envoy/http/mixer/config.h:37
#2  0x00000000004d415b in Envoy::Http::Mixer::Control::Control (this=0x4a15870, config=..., cm=..., dispatcher=..., random=..., scope=..., stats=..., local_info=...)
    at src/envoy/http/mixer/control.cc:33
#3  0x00000000004ec214 in __gnu_cxx::new_allocator<Envoy::Http::Mixer::Control>::construct<Envoy::Http::Mixer::Control, Envoy::Http::Mixer::Config&, Envoy::Upstream::ClusterManager&, Envoy::Event::Dispatcher&, Envoy::Runtime::RandomGenerator&, Envoy::Stats::Scope&, Envoy::Utils::MixerFilterStats&, Envoy::LocalInfo::LocalInfo const&> (this=0x7f8450bfc2b8, __p=0x4a15870, __args=...,
    __args=..., __args=..., __args=..., __args=..., __args=..., __args=...) at /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/ext/new_allocator.h:120
#4  0x00000000004ebf2b in std::allocator_traits<std::allocator<Envoy::Http::Mixer::Control> >::construct<Envoy::Http::Mixer::Control, Envoy::Http::Mixer::Config&, Envoy::Upstream::ClusterManager&, Envoy::Event::Dispatcher&, Envoy::Runtime::RandomGenerator&, Envoy::Stats::Scope&, Envoy::Utils::MixerFilterStats&, Envoy::LocalInfo::LocalInfo const&> (__a=..., __p=0x4a15870, __args=...,
    __args=..., __args=..., __args=..., __args=..., __args=..., __args=...) at /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/bits/alloc_traits.h:530
#5  0x00000000004ebc2a in std::_Sp_counted_ptr_inplace<Envoy::Http::Mixer::Control, std::allocator<Envoy::Http::Mixer::Control>, (__gnu_cxx::_Lock_policy)2>::_Sp_counted_ptr_inplace<Envoy::Http::Mixer::Config&, Envoy::Upstream::ClusterManager&, Envoy::Event::Dispatcher&, Envoy::Runtime::RandomGenerator&, Envoy::Stats::Scope&, Envoy::Utils::MixerFilterStats&, Envoy::LocalInfo::LocalInfo const&> (this=0x4a15860, __a=..., __args=..., __args=..., __args=..., __args=..., __args=..., __args=..., __args=...)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/bits/shared_ptr_base.h:522
#6  0x00000000004eb95c in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count<Envoy::Http::Mixer::Control, std::allocator<Envoy::Http::Mixer::Control>, Envoy::Http::Mixer::Config&, Envoy::Upstream::ClusterManager&, Envoy::Event::Dispatcher&, Envoy::Runtime::RandomGenerator&, Envoy::Stats::Scope&, Envoy::Utils::MixerFilterStats&, Envoy::LocalInfo::LocalInfo const&> (
    this=0x7f8450bfc698, __a=..., __args=..., __args=..., __args=..., __args=..., __args=..., __args=..., __args=...)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/bits/shared_ptr_base.h:617
#7  0x00000000004eb785 in std::__shared_ptr<Envoy::Http::Mixer::Control, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<std::allocator<Envoy::Http::Mixer::Control>, Envoy::Http::Mixer::Config&, Envoy::Upstream::ClusterManager&, Envoy::Event::Dispatcher&, Envoy::Runtime::RandomGenerator&, Envoy::Stats::Scope&, Envoy::Utils::MixerFilterStats&, Envoy::LocalInfo::LocalInfo const&> (
    this=0x7f8450bfc690, __tag=..., __a=..., __args=..., __args=..., __args=..., __args=..., __args=..., __args=..., __args=...)
```

backtrace 
```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/local/bin/envoy -c /etc/istio/proxy/envoy-rev0.json --restart-epoch 0 --dr'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000000000046b6e0 in Envoy::Http::Mixer::Control::Control(Envoy::Http::Mixer::Config const&, Envoy::Upstream::ClusterManager&, Envoy::Event::Dispatcher&, Envoy::Runtime::RandomGenerator&, Envoy::Stats::Scope&, Envoy::Utils::MixerFilterStats&, Envoy::LocalInfo::LocalInfo const&) ()
[Current thread is 1 (Thread 0x7f1055b81700 (LWP 330))]
(gdb) bt
#0  0x000000000046b6e0 in Envoy::Http::Mixer::Control::Control(Envoy::Http::Mixer::Config const&, Envoy::Upstream::ClusterManager&, Envoy::Event::Dispatcher&, Envoy::Runtime::RandomGenerator&, Envoy::Stats::Scope&, Envoy::Utils::MixerFilterStats&, Envoy::LocalInfo::LocalInfo const&) ()
#1  0x0000000000475b1a in std::_Function_handler<std::shared_ptr<Envoy::ThreadLocal::ThreadLocalObject> (Envoy::Event::Dispatcher&), Envoy::Http::Mixer::ControlFactory::ControlFactory(std::unique_ptr<Envoy::Http::Mixer::Config, std::default_delete<Envoy::Http::Mixer::Config> >, Envoy::Server::Configuration::FactoryContext&)::{lambda(Envoy::Event::Dispatcher&)#1}>::_M_invoke(std::_Any_data const&, Envoy::Event::Dispatcher&) ()
#2  0x00000000007d55fd in std::_Function_handler<void (), Envoy::ThreadLocal::InstanceImpl::SlotImpl::set(std::function<std::shared_ptr<Envoy::ThreadLocal::ThreadLocalObject> (Envoy::Event::Dispatcher&)>)::$_3>::_M_invoke(std::_Any_data const&) ()
#3  0x0000000000811b6d in Envoy::Event::DispatcherImpl::runPostCallbacks() ()
#4  0x0000000000811a1d in Envoy::Event::DispatcherImpl::run(Envoy::Event::Dispatcher::RunType) ()
#5  0x000000000080d5e5 in Envoy::Server::WorkerImpl::threadRoutine(Envoy::Server::GuardDog&) ()
#6  0x0000000000bb800e in Envoy::Thread::Thread::Thread(std::function<void ()>)::$_0::__invoke(void*) ()
#7  0x00007f105a70d6ba in start_thread (arg=0x7f1055b81700) at pthread_create.c:333
#8  0x00007f105a13a41d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

### PR DESCRIPTION
**Pull request by JimmyCYJ**
**What this PR does / why we need it**:
Improves the fix https://github.com/istio/proxy/pull/2080 by using shared_ptr to protect uuid and stats.
 
**Which issue this PR fixes** : 
fixes #2079 

**Release note**:
```NONE
```

### CODE REVIEW

File: src/envoy/tcp/mixer/control_factory.h [hunk 1]
```diff
@@ -62,14 +62,12 @@ class ControlFactory : public Logger::Loggable<Logger::Id::filter> {
...
-  // The cluster manager
-  Upstream::ClusterManager& cm_;
   // the thread local slots
   ThreadLocal::SlotPtr tls_;
   // The statistics struct.
-  Utils::MixerFilterStats stats_;
+  std::shared_ptr<Utils::MixerFilterStats> stats_;
   // UUID of the Envoy TCP mixer filter.
-  const std::string uuid_;
+  std::shared_ptr<const std::string> uuid_;
```
Comment (qiwzhang) [inline src/envoy/tcp/mixer/control_factory.h]: No,  shared_ptr for these two variables is over-kill.

I believe stats_ itself is already "&".     uuid is a string, we can copy that string to the capture.

Comment (qiwzhang) [reply src/envoy/tcp/mixer/control_factory.h]: How about this idea:

Add a new class ControlData to hold all ControlFactory data except tls_

ControlFactory will hold 

tls_
and shared_ptr<ControlData>,

ControlDataSharedPtr will pass to Lambda to make sure

Comment (JimmyCYJ) [reply src/envoy/tcp/mixer/control_factory.h]: Per discussion, I will create std::shared_ptr<ControlFactoryData>, and move cm_, stats_, uuid_, and config_ into ControlFactoryData. I will pass ControlFactoryData into capture list.

**Comment by kyessenov** [comment]
Jimmy, can you make sure istio tests pass with this fix?
You can use `ENVOY_PATH` variable to override envoy binary in `mixer/test/client` tests.
We don't want to have a broken build (istio + proxy) for too long.

**Comment by JimmyCYJ** [comment]
> Jimmy, can you make sure istio tests pass with this fix?
> You can use `ENVOY_PATH` variable to override envoy binary in `mixer/test/client` tests.
> We don't want to have a broken build (istio + proxy) for too long.

I have built and tested the binary in istio.io/istio, and all tests in mixer/test/client passed.

File: src/envoy/tcp/mixer/control_factory.h (hunk 1 above)
Comment (JimmyCYJ) [reply src/envoy/tcp/mixer/control_factory.h]: Added ControlDataSharedPtr control_data_ into ControlFactory.

File: src/envoy/tcp/mixer/control.cc [hunk 2]
```diff
@@ -25,21 +25,20 @@ namespace Envoy {
 namespace Tcp {
 namespace Mixer {
 
-Control::Control(const Config& config, Upstream::ClusterManager& cm,
-                 Event::Dispatcher& dispatcher,
+Control::Control(ControlDataSharedPtr control_data,
```
Comment (qiwzhang) [inline src/envoy/tcp/mixer/control.cc]: Why pass in shared_ptr?   If you don't want "Control" to increase ref,  don't pass in shared_ptr.   Just pass in "const &"

File: src/envoy/tcp/mixer/control.h [hunk 3]
```diff
@@ -30,13 +30,30 @@ namespace Envoy {
...
+  const std::string uuid_;
+};
+
+typedef std::shared_ptr<ControlData> ControlDataSharedPtr;
+
 class Control final : public ThreadLocal::ThreadLocalObject {
  public:
   // The constructor.
-  Control(const Config& config, Upstream::ClusterManager& cm,
+  Control(ControlDataSharedPtr control_data, Upstream::ClusterManager& cm,
```
Comment (qiwzhang) [inline src/envoy/tcp/mixer/control.h]: not to use share_ptr here

File: src/envoy/http/mixer/control.h [hunk 4]
```diff
@@ -32,14 +32,28 @@ namespace Envoy {
...
+};
+
+typedef std::shared_ptr<ControlData> ControlDataSharedPtr;
+
 // The control object created per-thread.
 class Control final : public ThreadLocal::ThreadLocalObject {
  public:
   // The constructor.
-  Control(const Config& config, Upstream::ClusterManager& cm,
+  Control(ControlDataSharedPtr control_data, Upstream::ClusterManager& cm,
```
Comment (qiwzhang) [inline src/envoy/http/mixer/control.h]: not to pass in shared_ptr

File: src/envoy/tcp/mixer/control.cc (hunk 2 above)
Comment (JimmyCYJ) [reply src/envoy/tcp/mixer/control.cc]: Changed to ControlData& control_data. We cannot pass const ControlData& because control_data.stats() could not become const.

Comment (lizan) [reply src/envoy/tcp/mixer/control.cc]: In this case, couldn't config_ be a dangling pointer when ControlFactory is gone?

Comment (JimmyCYJ) [reply src/envoy/tcp/mixer/control.cc]: I am not clear with this comment. Are you saying that passing ControlData& control_data is not safe, control_data is destroyed when ControlFactory is gone? We pass ControlDataSharedPtr control_data_ into capture list, that increases the ref count, no?

Comment (lizan) [reply src/envoy/tcp/mixer/control.cc]: ThreadLocalObject::set does't hold the lambda, it just post to all worker thread. So once the execution is done, the only ref of ControlDataSharedPtr is ControlFactory, and since Control holds config as const reference, it might be dangling if ControlFactory is gone.

Comment (qiwzhang) [reply src/envoy/tcp/mixer/control.cc]: The question is: will Control (the object stored in each thread local slot) out-live ControlFactory.    Or another word, Will the object stored in tls_ out live tls_ itself?  I guess the answer is yes, the it is better to pass the ControlDataSharedPtr to Control and Control has to hold a reference count

Comment (lizan) [reply src/envoy/tcp/mixer/control.cc]: > object stored in tls_ out live tls_ itself

Yes, slot destroy all data by posting callback to all dispatchers.

Comment (JimmyCYJ) [reply src/envoy/tcp/mixer/control.cc]: I add a member ControlDataSharedPtr control_data_ into Http::Mixer::Control and Tcp::Mixer::Control, and add a JwtAuthenticationConstSharedPtr config_ into JwtAuthStore. This is to guarantee that each worker thread hold a ref to the shared config, and the config ref count is always positive. So that even ControlFactory or JwtAuthStoreFactore is gone, JwtAuthStore and Control objects do not cause envoy to crash.

Comment (JimmyCYJ) [reply src/envoy/tcp/mixer/control.cc]: Please take a look. I have built and run binary in istio.io/istio and all tests pass.

Comment (kyessenov) [reply src/envoy/tcp/mixer/control.cc]: Thanks for manually testing against istio/istio.

File: src/envoy/tcp/mixer/control_factory.h [hunk 5]
```diff
@@ -32,21 +32,20 @@ class ControlFactory : public Logger::Loggable<Logger::Id::filter> {
...
-    tls_->set([config = this->config_, &cm = this->cm_, uuid = this->uuid_,
-               &stats = this->stats_, &random, &scope,
+    tls_->set([control_data = this->control_data_,
+               &cm = context.clusterManager(), &random, &scope,
                &local_info](Event::Dispatcher& dispatcher)
                   -> ThreadLocal::ThreadLocalObjectSharedPtr {
-      return ThreadLocal::ThreadLocalObjectSharedPtr(new Control(
-          *config, cm, dispatcher, random, scope, stats, uuid, local_info));
+      return ThreadLocal::ThreadLocalObjectSharedPtr(
+          new Control(control_data, cm, dispatcher, random, scope, local_info));
```
Comment (lizan) [inline src/envoy/tcp/mixer/control_factory.h]: nit: make_shared where possible

Comment (JimmyCYJ) [reply src/envoy/tcp/mixer/control_factory.h]: Done. Thanks!

**Comment by JimmyCYJ** [comment]
Thanks for reviewing this PR, @qiwzhang and @lizan. Removed hold label to let it in.
