### PR TITLE
Removes dangling pointer in capture list of lambda function.

### LINKED ISSUE #2079: SIGSEGV with gcr.io/istio-release/proxyv2:release-1.1-20181222-09-15
```
2019-01-12T01:31:06.256829Z	info	Reconciling retry (budget 3)
2019-01-12T01:31:06.256962Z	info	Epoch 0 starting
2019-01-12T01:31:06.258207Z	info	Envoy command: [-c /etc/istio/proxy/envoy-rev0.json --restart-epoch 0 --drain-time-s 45 --parent-shutdown-time-s 60 --service-cluster istio-ingressgateway --service-node router~10.44.3.12~istio-ingressgateway-b77977775-h56ft.istio-system~istio-system.svc.cluster.local --max-obj-name-len 189 --allow-unknown-fields -l warning --v2-config-only]
[2019-01-12 01:31:06.291][000262][warning][upstream] [external/envoy/source/common/config/grpc_mux_impl.cc:268] gRPC config stream closed: 14, no healthy upstream
[2019-01-12 01:31:06.291][000262][warning][upstream] [external/envoy/source/common/config/grpc_mux_impl.cc:51] Unable to establish new stream
[2019-01-12 01:31:06.761][000262][warning][config] [src/envoy/utils/mixer_control.cc:171] ExtractInfo  metadata missing:
[2019-01-12 01:31:06.762][000262][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_mux_subscription_lib/common/config/grpc_mux_subscription_impl.h:70] gRPC config for type.googleapis.com/envoy.api.v2.Listener rejected: Error adding/updating listener 0.0.0.0_443: error adding listener '0.0.0.0:443': multiple filter chains with the same matching rules are defined
[2019-01-12 01:31:06.770][000268][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:125] Caught Segmentation fault, suspect faulting address 0x80
2019-01-12T01:31:06.851486Z	warn	Epoch 0 terminated with an error: signal: segmentation fault (core dumped)
2019-01-12T01:31:06.851575Z	warn	Aborted all epochs
```

debug backtrace
```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/local/bin/envoy -c /etc/istio/proxy/envoy-rev0.json --restart-epoch 0 --dr'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  istio::mixer::v1::config::client::HttpClientConfig::transport (this=0x0) at bazel-out/k8-dbg/genfiles/external/mixerapi_git/mixer/v1/config/client/client_config.pb.h:1533
1533	bazel-out/k8-dbg/genfiles/external/mixerapi_git/mixer/v1/config/client/client_config.pb.h: No such file or directory.
[Current thread is 1 (Thread 0x7f8450c0f700 (LWP 520))]
(gdb) bt
#0  istio::mixer::v1::config::client::HttpClientConfig::transport (this=0x0) at bazel-out/k8-dbg/genfiles/external/mixerapi_git/mixer/v1/config/client/client_config.pb.h:1533
#1  0x00000000004d4ca5 in Envoy::Http::Mixer::Config::check_cluster[abi:cxx11]() const (this=0x0) at ./src/envoy/http/mixer/config.h:37
#2  0x00000000004d415b in Envoy::Http::Mixer::Control::Control (this=0x4a15870, config=..., cm=..., dispatcher=..., random=..., scope=..., stats=..., local_info=...)
    at src/envoy/http/mixer/control.cc:33
#3  0x00000000004ec214 in __gnu_cxx::new_allocator<Envoy::Http::Mixer::Control>::construct<Envoy::Http::Mixer::Control, Envoy::Http::Mixer::Config&, Envoy::Upstream::ClusterManager&, Envoy::Event::Dispatcher&, Envoy::Runtime::RandomGenerator&, Envoy::Stats::Scope&, Envoy::Utils::MixerFilterStats&, Envoy::LocalInfo::LocalInfo const&> (this=0x7f8450bfc2b8, __p=0x4a15870, __args=...,
    __args=..., __args=..., __args=..., __args=..., __args=..., __args=...) at /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/ext/new_allocator.h:120
#4  0x00000000004ebf2b in std::allocator_traits<std::allocator<Envoy::Http::Mixer::Control> >::construct<Envoy::Http::Mixer::Control, Envoy::Http::Mixer::Config&, Envoy::Upstream::ClusterManager&, Envoy::Event::Dispatcher&, Envoy::Runtime::RandomGenerator&, Envoy::Stats::Scope&, Envoy::Utils::MixerFilterStats&, Envoy::LocalInfo::LocalInfo const&> (__a=..., __p=0x4a15870, __args=...,
    __args=..., __args=..., __args=..., __args=..., __args=..., __args=...) at /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/bits/alloc_traits.h:530
#5  0x00000000004ebc2a in std::_Sp_counted_ptr_inplace<Envoy::Http::Mixer::Control, std::allocator<Envoy::Http::Mixer::Control>, (__gnu_cxx::_Lock_policy)2>::_Sp_counted_ptr_inplace<Envoy::Http::Mixer::Config&, Envoy::Upstream::ClusterManager&, Envoy::Event::Dispatcher&, Envoy::Runtime::RandomGenerator&, Envoy::Stats::Scope&, Envoy::Utils::MixerFilterStats&, Envoy::LocalInfo::LocalInfo const&> (this=0x4a15860, __a=..., __args=..., __args=..., __args=..., __args=..., __args=..., __args=..., __args=...)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/bits/shared_ptr_base.h:522
#6  0x00000000004eb95c in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count<Envoy::Http::Mixer::Control, std::allocator<Envoy::Http::Mixer::Control>, Envoy::Http::Mixer::Config&, Envoy::Upstream::ClusterManager&, Envoy::Event::Dispatcher&, Envoy::Runtime::RandomGenerator&, Envoy::Stats::Scope&, Envoy::Utils::MixerFilterStats&, Envoy::LocalInfo::LocalInfo const&> (
    this=0x7f8450bfc698, __a=..., __args=..., __args=..., __args=..., __args=..., __args=..., __args=..., __args=...)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/bits/shared_ptr_base.h:617
#7  0x00000000004eb785 in std::__shared_ptr<Envoy::Http::Mixer::Control, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<std::allocator<Envoy::Http::Mixer::Control>, Envoy::Http::Mixer::Config&, Envoy::Upstream::ClusterManager&, Envoy::Event::Dispatcher&, Envoy::Runtime::RandomGenerator&, Envoy::Stats::Scope&, Envoy::Utils::MixerFilterStats&, Envoy::LocalInfo::LocalInfo const&> (
    this=0x7f8450bfc690, __tag=..., __a=..., __args=..., __args=..., __args=..., __args=..., __args=..., __args=..., __args=...)
```

backtrace 
```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/local/bin/envoy -c /etc/istio/proxy/envoy-rev0.json --restart-epoch 0 --dr'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000000000046b6e0 in Envoy::Http::Mixer::Control::Control(Envoy::Http::Mixer::Config const&, Envoy::Upstream::ClusterManager&, Envoy::Event::Dispatcher&, Envoy::Runtime::RandomGenerator&, Envoy::Stats::Scope&, Envoy::Utils::MixerFilterStats&, Envoy::LocalInfo::LocalInfo const&) ()
[Current thread is 1 (Thread 0x7f1055b81700 (LWP 330))]
(gdb) bt
#0  0x000000000046b6e0 in Envoy::Http::Mixer::Control::Control(Envoy::Http::Mixer::Config const&, Envoy::Upstream::ClusterManager&, Envoy::Event::Dispatcher&, Envoy::Runtime::RandomGenerator&, Envoy::Stats::Scope&, Envoy::Utils::MixerFilterStats&, Envoy::LocalInfo::LocalInfo const&) ()
#1  0x0000000000475b1a in std::_Function_handler<std::shared_ptr<Envoy::ThreadLocal::ThreadLocalObject> (Envoy::Event::Dispatcher&), Envoy::Http::Mixer::ControlFactory::ControlFactory(std::unique_ptr<Envoy::Http::Mixer::Config, std::default_delete<Envoy::Http::Mixer::Config> >, Envoy::Server::Configuration::FactoryContext&)::{lambda(Envoy::Event::Dispatcher&)#1}>::_M_invoke(std::_Any_data const&, Envoy::Event::Dispatcher&) ()
#2  0x00000000007d55fd in std::_Function_handler<void (), Envoy::ThreadLocal::InstanceImpl::SlotImpl::set(std::function<std::shared_ptr<Envoy::ThreadLocal::ThreadLocalObject> (Envoy::Event::Dispatcher&)>)::$_3>::_M_invoke(std::_Any_data const&) ()
#3  0x0000000000811b6d in Envoy::Event::DispatcherImpl::runPostCallbacks() ()
#4  0x0000000000811a1d in Envoy::Event::DispatcherImpl::run(Envoy::Event::Dispatcher::RunType) ()
#5  0x000000000080d5e5 in Envoy::Server::WorkerImpl::threadRoutine(Envoy::Server::GuardDog&) ()
#6  0x0000000000bb800e in Envoy::Thread::Thread::Thread(std::function<void ()>)::$_0::__invoke(void*) ()
#7  0x00007f105a70d6ba in start_thread (arg=0x7f1055b81700) at pthread_create.c:333
#8  0x00007f105a13a41d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

### PR DESCRIPTION
**Pull request by JimmyCYJ**
**What this PR does / why we need it**:
The ControlFactory for HTTP Mixer filter post a callback into worker threads' dispatcher, which will be invoked by event loop. The callback is a lambda function that has a this pointer in the capture list, and the pointer points to ControlFactory. When Envoy rejects a bad listener config, the ControlFactory is destructed accordingly, and therefore the "this" pointer becomes dangling pointer. TCP Mixer filter and JwtAuthStoreFactory have the same issue, too. This PR removes "this" pointer from capture list, and passes shared_ptr of components that are needed by the lambda function. Tests will be added in a following PR.

**Which issue this PR fixes** : 
fixes #2079 

**Release note**:
```NONE
```

### CODE REVIEW

File: src/envoy/http/jwt_auth/auth_store.h [hunk 1]
```diff
@@ -66,21 +66,25 @@ class JwtAuthStoreFactory : public Logger::Loggable<Logger::Id::config> {
...
-        [this](Event::Dispatcher&) -> ThreadLocal::ThreadLocalObjectSharedPtr {
-          return std::make_shared<JwtAuthStore>(config_);
-        });
+      : config_(
+            std::make_shared<::istio::envoy::config::filter::http::jwt_auth::
+                                 v2alpha1::JwtAuthentication>(config)),
+        tls_(context.threadLocal().allocateSlot()) {
+    tls_->set([config = this->config_](Event::Dispatcher&)
+                  -> ThreadLocal::ThreadLocalObjectSharedPtr {
+      return std::make_shared<JwtAuthStore>(*config);
```
Comment (PiotrSikora) [inline src/envoy/http/jwt_auth/auth_store.h]: Do we need to create shared-pointer from shared-pointer? Can't we re-use the existing one?
```
tls_->set([config = this->config_](Event::Dispatcher&)
              -> ThreadLocal::ThreadLocalObjectSharedPtr { return config; }
```

Comment (PiotrSikora) [reply src/envoy/http/jwt_auth/auth_store.h]: Actually, nevermind, it's different type. Sorry for the noise.

Comment (lizan) [reply src/envoy/http/jwt_auth/auth_store.h]: different type? config is proto and JwtAuthStore is not.

Comment (JimmyCYJ) [reply src/envoy/http/jwt_auth/auth_store.h]: Yes they are different types.

It seems that the change to ControlFactory in tcp/mixer/control_factory.h causes Envoy crash.
It can be reproduced under istio.io/istio by 
$ go test -v mixer/test/client/tcp_filter/tcp_filter_test.go,  or
$ go test -v mixer/test/client/pilotplugin_tcp/pilotplugin_tcp_test.go
https://github.com/istio/istio/pull/10987 fails at these two test.

I build the proxy binary and run tcp_filter_test.go locally, and get this output.
2019-01-15T23:25:26.198319Z	info	15:25:26 Short live HTTP POST http://localhost:20121/echo
[libprotobuf ERROR external/com_google_protobuf/src/google/protobuf/wire_format_lite.cc:625] String field 'istio.mixer.v1.CompressedAttributes.words' contains invalid UTF-8 data when serializing a protocol buffer. Use the 'bytes' type if you intend to send raw bytes. 
[libprotobuf INFO src/istio/mixerclient/check_cache.cc:160] Add a new Referenced for check cache: Absence-keys: Exact-keys: connection.id, connection.mtls, context.protocol, context.reporter.uid, context.time, destination.namespace, destination.uid, mesh1.ip, origin.ip, source.ip, target.namespace, target.uid, 
2019-01-15T23:25:26.205587Z	info	15:25:26 Hello World!
[libprotobuf ERROR external/com_google_protobuf/src/google/protobuf/wire_format_lite.cc:625] String field 'istio.mixer.v1.ReportRequest.default_words' contains invalid UTF-8 data when serializing a protocol buffer. Use the 'bytes' type if you intend to send raw bytes. 
2019-01-15T23:25:27.207326Z	info	15:25:27 Short live HTTP POST http://localhost:20121/echo
tcmalloc: large alloc 94105249480704 bytes == (nil) @  0x559694eee0ce 0x559694fb225b 0x559693bb5b32 0x559694f690ef 0x559693c52101 0x559693c5d6fb 0x559693c5c289 0x559693c50fa6 0x559693c512f3 0x5596943f03d7 0x5596943f04ee 0x5596943e7756 0x5596943e8e09 0x5596943e8ba7 0x5596943e552f 0x5596943eab49 0x5596943de488 0x5596943de1de 0x5596943de25c 0x559694a1c59b 0x559694a1cb7f 0x559694a20700 0x5596943d97e6 0x5596943caacd 0x5596943ca39c 0x5596943cb3db 0x559693c14730 0x559694e90f3c 0x559694e90f60 0x7f90d4cae494
[2019-01-15 15:25:27.209][184436][critical][main] [external/envoy/source/exe/terminate_handler.cc:13] std::terminate called! (possible uncaught exception, see trace)
[2019-01-15 15:25:27.209][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:94] Backtrace thr<184436> obj</usr/local/google/home/yinjie/go/bin/envoy> (If unsymbolized, use tools/stack_decode.py):
[2019-01-15 15:25:27.235][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] thr<184436> #0 0x559694e8eb7c backward::details::unwind<>()
[2019-01-15 15:25:27.253][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] thr<184436> #1 0x559694e8dd66 backward::StackTraceImpl<>::load_here()
[2019-01-15 15:25:27.271][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] thr<184436> #2 0x559694e8e408 Envoy::BackwardsTrace::capture()
[2019-01-15 15:25:27.288][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] thr<184436> #3 0x559694e9084f Envoy::TerminateHandler::logOnTerminate()::{lambda()#1}::operator()()
[2019-01-15 15:25:27.306][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] thr<184436> #4 0x559694e90894 Envoy::TerminateHandler::logOnTerminate()::{lambda()#1}::_FUN()
[2019-01-15 15:25:27.324][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] thr<184436> #5 0x559694f0da45 __cxxabiv1::__terminate()
[2019-01-15 15:25:27.341][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] thr<184436> #6 0x559694f0da90 std::terminate()
[2019-01-15 15:25:27.359][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] thr<184436> #7 0x559694f0dc13 __cxa_throw
[2019-01-15 15:25:27.376][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] thr<184436> #8 0x559694eed997 (anonymous namespace)::handle_oom()
[2019-01-15 15:25:27.394][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] thr<184436> #9 0x559694fb21cd tcmalloc::allocate_full_cpp_throw_oom()
[2019-01-15 15:25:27.411][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] thr<184436> #10 0x559693bb5b31 std::__cxx11::basic_string<>::_M_construct<>()
[2019-01-15 15:25:27.428][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] thr<184436> #11 0x559694f690ee std::__cxx11::basic_string<>::basic_string()
[2019-01-15 15:25:27.446][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] thr<184436> #12 0x559693bb2a7e std::operator+<>()
[2019-01-15 15:25:27.463][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] thr<184436> #13 0x559693c52100 _ZNK5Envoy3Tcp5Mixer6Filter15GetConnectionIdB5cxx11Ev
[2019-01-15 15:25:27.480][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] thr<184436> #14 0x559693c5d6fa istio::control::tcp::AttributesBuilder::ExtractCheckAttributes()
[2019-01-15 15:25:27.497][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] thr<184436> #15 0x559693c5c288 istio::control::tcp::RequestHandlerImpl::Check()
[2019-01-15 15:25:27.514][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] thr<184436> #16 0x559693c50fa5 Envoy::Tcp::Mixer::Filter::callCheck()
[2019-01-15 15:25:27.531][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] thr<184436> #17 0x559693c512f2 Envoy::Tcp::Mixer::Filter::onData()
[2019-01-15 15:25:27.549][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] thr<184436> #18 0x5596943f03d6 Envoy::Network::FilterManagerImpl::onContinueReading()
[2019-01-15 15:25:27.565][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] thr<184436> #19 0x5596943f04ed Envoy::Network::FilterManagerImpl::onRead()
[2019-01-15 15:25:27.582][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] thr<184436> #20 0x5596943e7755 Envoy::Network::ConnectionImpl::onRead()
[2019-01-15 15:25:27.598][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] thr<184436> #21 0x5596943e8e08 Envoy::Network::ConnectionImpl::onReadReady()
[2019-01-15 15:25:27.615][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] thr<184436> #22 0x5596943e8ba6 Envoy::Network::ConnectionImpl::onFileEvent()
[2019-01-15 15:25:27.631][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] thr<184436> #23 0x5596943e552e Envoy::Network::ConnectionImpl::ConnectionImpl()::{lambda()#3}::operator()()
[2019-01-15 15:25:27.647][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] thr<184436> #24 0x5596943eab48 std::_Function_handler<>::_M_invoke()
[2019-01-15 15:25:27.664][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] thr<184436> #25 0x5596943de487 std::function<>::operator()()
[2019-01-15 15:25:27.680][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] thr<184436> #26 0x5596943de1dd Envoy::Event::FileEventImpl::assignEvents()::{lambda()#1}::operator()()
[2019-01-15 15:25:27.696][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] thr<184436> #27 0x5596943de25b Envoy::Event::FileEventImpl::assignEvents()::{lambda()#1}::_FUN()
[2019-01-15 15:25:27.713][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] thr<184436> #28 0x559694a1c59a event_process_active_single_queue.isra.29
[2019-01-15 15:25:27.729][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] thr<184436> #29 0x559694a1cb7e event_process_active
[2019-01-15 15:25:27.745][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] thr<184436> #30 0x559694a206ff event_base_loop
[2019-01-15 15:25:27.762][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] thr<184436> #31 0x5596943d97e5 Envoy::Event::DispatcherImpl::run()
[2019-01-15 15:25:27.778][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] thr<184436> #32 0x5596943caacc Envoy::Server::WorkerImpl::threadRoutine()
[2019-01-15 15:25:27.795][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] thr<184436> #33 0x5596943ca39b Envoy::Server::WorkerImpl::start()::{lambda()#1}::operator()()
[2019-01-15 15:25:27.811][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] thr<184436> #34 0x5596943cb3da std::_Function_handler<>::_M_invoke()
[2019-01-15 15:25:27.827][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] thr<184436> #35 0x559693c1472f std::function<>::operator()()
[2019-01-15 15:25:27.843][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] thr<184436> #36 0x559694e90f3b Envoy::Thread::ThreadImplPosix::ThreadImplPosix()::{lambda()#1}::operator()()
[2019-01-15 15:25:27.860][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] thr<184436> #37 0x559694e90f5f Envoy::Thread::ThreadImplPosix::ThreadImplPosix()::{lambda()#1}::_FUN()
[2019-01-15 15:25:27.860][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:104] thr<184436> obj</lib/x86_64-linux-gnu/libpthread.so.0>
[2019-01-15 15:25:27.860][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] thr<184436> #38 0x7f90d4cae493 start_thread
[2019-01-15 15:25:27.860][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:104] thr<184436> obj</lib/x86_64-linux-gnu/libc.so.6>
[2019-01-15 15:25:27.860][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:117] thr<184436> #39 0x7f90d46eca8e (unknown)
[2019-01-15 15:25:27.860][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:121] end backtrace thread 184436
[2019-01-15 15:25:27.860][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:125] Caught Aborted, suspect faulting address 0x3b5be0002d06d
[2019-01-15 15:25:27.860][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:94] Backtrace thr<184436> obj</lib/x86_64-linux-gnu/libc.so.6> (If unsymbolized, use tools/stack_decode.py):
[2019-01-15 15:25:27.860][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:117] thr<184436> #0 0x7f90d4636fcf (unknown)
[2019-01-15 15:25:27.860][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:117] thr<184436> #1 0x7f90d46383f9 (unknown)
[2019-01-15 15:25:27.860][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:104] thr<184436> obj</usr/local/google/home/yinjie/go/bin/envoy>
[2019-01-15 15:25:27.877][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] thr<184436> #2 0x559694e9086c Envoy::TerminateHandler::logOnTerminate()::{lambda()#1}::operator()()
[2019-01-15 15:25:27.877][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] thr<184436> #3 0x559694e90894 Envoy::TerminateHandler::logOnTerminate()::{lambda()#1}::_FUN()
[2019-01-15 15:25:27.877][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] thr<184436> #4 0x559694f0da45 __cxxabiv1::__terminate()
[2019-01-15 15:25:27.877][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] thr<184436> #5 0x559694f0da90 std::terminate()
[2019-01-15 15:25:27.877][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] thr<184436> #6 0x559694f0dc13 __cxa_throw
[2019-01-15 15:25:27.877][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] thr<184436> #7 0x559694eed997 (anonymous namespace)::handle_oom()
[2019-01-15 15:25:27.877][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] thr<184436> #8 0x559694fb21cd tcmalloc::allocate_full_cpp_throw_oom()
[2019-01-15 15:25:27.877][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] thr<184436> #9 0x559693bb5b31 std::__cxx11::basic_string<>::_M_construct<>()
[2019-01-15 15:25:27.877][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] thr<184436> #10 0x559694f690ee std::__cxx11::basic_string<>::basic_string()
[2019-01-15 15:25:27.877][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] thr<184436> #11 0x559693bb2a7e std::operator+<>()
[2019-01-15 15:25:27.877][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] thr<184436> #12 0x559693c52100 _ZNK5Envoy3Tcp5Mixer6Filter15GetConnectionIdB5cxx11Ev
[2019-01-15 15:25:27.877][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] thr<184436> #13 0x559693c5d6fa istio::control::tcp::AttributesBuilder::ExtractCheckAttributes()
[2019-01-15 15:25:27.877][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] thr<184436> #14 0x559693c5c288 istio::control::tcp::RequestHandlerImpl::Check()
[2019-01-15 15:25:27.877][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] thr<184436> #15 0x559693c50fa5 Envoy::Tcp::Mixer::Filter::callCheck()
[2019-01-15 15:25:27.877][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] thr<184436> #16 0x559693c512f2 Envoy::Tcp::Mixer::Filter::onData()
[2019-01-15 15:25:27.877][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] thr<184436> #17 0x5596943f03d6 Envoy::Network::FilterManagerImpl::onContinueReading()
[2019-01-15 15:25:27.877][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] thr<184436> #18 0x5596943f04ed Envoy::Network::FilterManagerImpl::onRead()
[2019-01-15 15:25:27.877][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] thr<184436> #19 0x5596943e7755 Envoy::Network::ConnectionImpl::onRead()
[2019-01-15 15:25:27.877][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] thr<184436> #20 0x5596943e8e08 Envoy::Network::ConnectionImpl::onReadReady()
[2019-01-15 15:25:27.877][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] thr<184436> #21 0x5596943e8ba6 Envoy::Network::ConnectionImpl::onFileEvent()
[2019-01-15 15:25:27.877][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] thr<184436> #22 0x5596943e552e Envoy::Network::ConnectionImpl::ConnectionImpl()::{lambda()#3}::operator()()
[2019-01-15 15:25:27.877][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] thr<184436> #23 0x5596943eab48 std::_Function_handler<>::_M_invoke()
[2019-01-15 15:25:27.877][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] thr<184436> #24 0x5596943de487 std::function<>::operator()()
[2019-01-15 15:25:27.877][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] thr<184436> #25 0x5596943de1dd Envoy::Event::FileEventImpl::assignEvents()::{lambda()#1}::operator()()
[2019-01-15 15:25:27.877][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] thr<184436> #26 0x5596943de25b Envoy::Event::FileEventImpl::assignEvents()::{lambda()#1}::_FUN()
[2019-01-15 15:25:27.877][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] thr<184436> #27 0x559694a1c59a event_process_active_single_queue.isra.29
[2019-01-15 15:25:27.877][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] thr<184436> #28 0x559694a1cb7e event_process_active
[2019-01-15 15:25:27.877][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] thr<184436> #29 0x559694a206ff event_base_loop
[2019-01-15 15:25:27.877][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] thr<184436> #30 0x5596943d97e5 Envoy::Event::DispatcherImpl::run()
[2019-01-15 15:25:27.877][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] thr<184436> #31 0x5596943caacc Envoy::Server::WorkerImpl::threadRoutine()
[2019-01-15 15:25:27.877][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] thr<184436> #32 0x5596943ca39b Envoy::Server::WorkerImpl::start()::{lambda()#1}::operator()()
[2019-01-15 15:25:27.877][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] thr<184436> #33 0x5596943cb3da std::_Function_handler<>::_M_invoke()
[2019-01-15 15:25:27.877][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] thr<184436> #34 0x559693c1472f std::function<>::operator()()
[2019-01-15 15:25:27.877][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] thr<184436> #35 0x559694e90f3b Envoy::Thread::ThreadImplPosix::ThreadImplPosix()::{lambda()#1}::operator()()
[2019-01-15 15:25:27.877][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] thr<184436> #36 0x559694e90f5f Envoy::Thread::ThreadImplPosix::ThreadImplPosix()::{lambda()#1}::_FUN()
[2019-01-15 15:25:27.877][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:104] thr<184436> obj</lib/x86_64-linux-gnu/libpthread.so.0>
[2019-01-15 15:25:27.877][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:114] thr<184436> #37 0x7f90d4cae493 start_thread
[2019-01-15 15:25:27.877][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:104] thr<184436> obj</lib/x86_64-linux-gnu/libc.so.6>
[2019-01-15 15:25:27.877][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:117] thr<184436> #38 0x7f90d46eca8e (unknown)
[2019-01-15 15:25:27.877][184436][critical][backtrace] [bazel-out/k8-fastbuild/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:121] end backtrace thread 184436
