### PR TITLE
Cancel check call on destroy

### LINKED ISSUE #438: proxy crash at race condition with LDS update
The back trace log is here:  https://pastebin.com/PUm4G5sC

The theory is  that Mixer Config is deleted by Mixer filter instance since the latter holds a ref count to the former (https://github.com/istio/proxy/blob/master/src/envoy/mixer/http_filter.cc#L132).  A filter instance deletion will be delayed if there is a gRPC call in the progress (https://github.com/istio/proxy/blob/master/src/envoy/mixer/http_filter.cc#L254).  When the grpc call is completed, the instance will be deleted at that thread.   Then mixer config will be deleted at that thread too.  

But since mixer config holds envoy thread local slot (https://github.com/istio/proxy/blob/master/src/envoy/mixer/http_filter.cc#L105).  It has to be deleted at main thread.  it causes assertion (https://github.com/lyft/envoy/blob/master/source/common/thread_local/thread_local_impl.cc#L58).

### PR DESCRIPTION
**Pull request by lizan**
depends on https://github.com/istio/mixerclient/pull/102

Fixes #438

### CODE REVIEW

File: src/envoy/mixer/tcp_filter.cc [hunk 1]
```diff
@@ -125,14 +131,12 @@ class TcpInstance : public Network::Filter,
...
       filter_callbacks_->connection().readDisable(true);
-      auto instance = GetPtr();
       calling_check_ = true;
       mixer_control_.BuildTcpCheck(
           request_data_, filter_callbacks_->connection(), origin_user);
-      mixer_control_.SendCheck(request_data_, nullptr,
-                               [instance](const Status& status) {
-                                 instance->completeCheck(status);
-                               });
+      mixer_control_.SendCheck(
```
Comment (qiwzhang) [inline src/envoy/mixer/tcp_filter.cc]: cancel_check callback need to be saved.
